site_name: fabric-cicd

repo_name: microsoft/fabric-cicd
repo_url: https://github.com/microsoft/fabric-cicd
site_url: https://microsoft.github.io/fabric-cicd/
remote_branch: gh-pages
remote_name: origin

nav:
    - Home: index.md
    - How To:
          - How To: how_to/index.md
          - Getting Started: how_to/getting_started.md
          - Item Types: how_to/item_types.md
          - Configuration Deployment: how_to/config_deployment.md
          - Parameterization: how_to/parameterization.md
          - Optional Features: how_to/optional_feature.md
          - Troubleshooting: how_to/troubleshooting.md
    - Examples:
          - Examples: example/index.md
          - Authentication: example/authentication.md
          - Deployment Variables: example/deployment_variable.md
          - Release Pipelines: example/release_pipeline.md
    - Code Reference: code_reference.md
    - Contribution: contribution.md
    - Changelog: changelog.md
    - About: about.md

theme:
    name: material
    custom_dir: docs/config/overrides
    icon:
        logo: fontawesome/solid/code
    favicon: config/assets/favicon.ico
    font:
        text: Roboto
        code: Roboto Mono

    features:
        - content.code.copy
        - content.tooltips
        - navigation.expand
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - search.highlight
        - search.suggest
        - toc.follow
        - toc.integrate
        - announce.dismiss
    language: en
    palette:
        scheme: fabric

extra_css:
    - config/stylesheets/extra.css
hooks:
    - docs/config/pre-build/update_item_types.py
    - docs/config/pre-build/section_toc.py
    - docs/config/pre-build/update_python_version.py

plugins:
    - search:
          separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    - minify:
          minify_html: true
    - include-markdown
    - mkdocstrings:
          handlers:
              python:
                  paths: ["src"]
                  options:
                      docstring_style: google
                      docstring_options:
                          ignore_init_summary: true
                      summary:
                          modules: false
                          functions: true
                          classes: true
                      show_source: false
                      show_root_full_path: false
                      separate_signature: true
                      show_signature_annotations: true
                      signature_crossrefs: true
                      filters: ["!^_", "^__init__$"]
                      merge_init_into_class: true
                      show_symbol_type_heading: true
                      show_symbol_type_toc: true
                      line_length: 80

extra:
    version:
        provider: mike
        default: latest
        alias: true
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/microsoft/fabric-cicd
    generator: false
    analytics:
        feedback:
        title: Was this page helpful?
        ratings:
            - icon: material/thumb-up-outline
              name: This page was helpful
              data: 1
              note: Thanks for your feedback!
            - icon: material/thumb-down-outline
              name: This page could be improved
              data: 0
              note: >-
                  Thanks for your feedback! Help us improve this page by using our 
                  <a href="https://github.com/microsoft/fabric-cicd/issues/new?template=3-documentation.yml&documentation-location={url}" target="_blank" rel="noopener">feedback form</a>.

markdown_extensions:
    - abbr
    - md_in_html
    - toc:
          permalink: true
    - admonition
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.superfences

copyright: Copyright Â© Microsoft Corporation
