core:
    workspace:
        dev: "fabricCICD_DevWS"
        prod: "fabricCICD_DeploymentWS"

    workspace_id:
        dev: "7d3cbf1d-affe-4286-aaa5-32e7e45107d7"
        prod: "5b39f77a-e111-429b-aa2b-d5ea3d67cd28"

    repository_directory: "." # relative path

    #item_types_in_scope:
    #    - Notebook
    #    - DataPipeline
    #    - Environment
    #    - Lakehouse

    parameter: "parameter.yml" # relative path

publish:
    # Don't publish items matching this pattern
    #exclude_regex: "^DONT_DEPLOY.*"

    #folder_exclude_regex: "^DONT_DEPLOY_FOLDER/"

    #items_to_include:
    #    - "Hello World.Notebook"
    #    - "Run Hello World.DataPipeline"

    skip:
        dev: true
        prod: false

unpublish:
    # Don't unpublish items matching this pattern
    exclude_regex: "^DEBUG.*"

    skip:
        dev: true
        prod: false

features:
    - enable_shortcut_publish
    - continue_on_shortcut_failure
    #- enable_experimental_features
    #- enable_items_to_include

constants:
    DEFAULT_API_ROOT_URL: "https://api.fabric.microsoft.com"
